### ISSUE TITLE
PHP-CS-Fixer

### ISSUE THREAD

**Issue by mlocati** [avalanche123/Imagine#606]
What about normalizing the coding style by using [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)?

I'm thinking about these rules (you can (re)configure them by importing them into [php-cs-fixer-configurator](https://mlocati.github.io/php-cs-fixer-configurator/?version=2.2#configurator)):

```yaml
version: 2.2.20
expandSets: true
fixerSets:
  - '@Symfony'
fixers:
  array_syntax: true
  blank_line_before_return: false
  dir_constant: true
  ereg_to_preg: true
  function_to_constant: true
  is_null:
    use_yoda_style: false
  no_alias_functions: true
  no_php4_constructor: true
  no_short_echo_tag: true
  no_unreachable_default_argument_value: true
  no_useless_return: true
  non_printable_character: true
  ordered_imports: true
  pre_increment: false
  phpdoc_add_missing_param_annotation:
    only_untyped: false
  phpdoc_align: false
  phpdoc_order: true
  protected_to_private: false
  psr4: true
risky: true
```
