### ISSUE TITLE
2.7 Mb animated GIF breaking the server

### ISSUE THREAD

**Issue by ThomasLabstep** [avalanche123/Imagine#680]
### Issue description

We are trying to resize a 2.7mb animated gif and it kills our server. On my mac, it reaches the timeout of 1min and uses 6gb of memory and 100% of cpu.

### What's the PHP version you are using?

```
PHP 7.1.13 (cli) (built: Feb  1 2018 13:38:42) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13, Copyright (c) 1999-2017, by Zend Technologies
```

### What's the imaging library you are using [gd/imagick/gmagick/any]?

```
Version: ImageMagick 7.0.8-11 Q16 x86_64 2018-08-29 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

### What's the imaging library configuration 

```
imagick

imagick module => enabled
imagick module version => 3.4.3
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version => ImageMagick 7.0.8-11 Q16 x86_64 2018-08-29 https://www.imagemagick.org
Imagick using ImageMagick library version => ImageMagick 7.0.8-11 Q16 x86_64 2018-08-29 https://www.imagemagick.org
ImageMagick copyright => © 1999-2018 ImageMagick Studio LLC
ImageMagick release date => 2018-08-29
ImageMagick number of supported formats:  => 222
ImageMagick supported formats => 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMV, WPG, X3F, XBM, XC, XCF, XPM, XPS, XV, YCbCr, YCbCrA, YUV

Directive => Local Value => Master Value
imagick.locale_fix => 0 => 0
imagick.skip_version_check => 0 => 0
imagick.progress_monitor => 0 => 0
```

### Minimal PHP code to reproduce the error: 

The code that I want to be able to disable is:

```
    /**
     * {@inheritdoc}
     */
    public function resize(BoxInterface $size, $filter = ImageInterface::FILTER_UNDEFINED)
    {
        try {
            if ($this->layers->count() > 1) {
                $this->imagick = $this->imagick->coalesceImages();
                foreach ($this->imagick as $frame) {
                    $frame->resizeImage($size->getWidth(), $size->getHeight(), $this->getFilter($filter), 1);
                }
                $this->imagick = $this->imagick->deconstructImages();
            } else {
                $this->imagick->resizeImage($size->getWidth(), $size->getHeight(), $this->getFilter($filter), 1);
            }
        } catch (\ImagickException $e) {
            throw new RuntimeException('Resize operation failed', $e->getCode(), $e);
        }
        return $this;
    }
```

How can we skip the "$this->layers->count() > 1" condition ?
For now we will fork this library to leave only the else part.
The dangerous code is "imagick->coalesceImages".
We don't want animated resized gif, only a thumbnail is fine for us.

We are using LiipImagine. They have a 'animated' option that is false by default. But we still go down to this method.

```
        file_small:
            data_loader: stream.amazon_s3
            quality: 100
            format: jpg
            filters:
                upscale:   { min:  [60, 60] }
                thumbnail: { size: [60, 60], mode: outbound, allow_upscale: true }
        file_medium:
            data_loader: stream.amazon_s3
            quality: 100
            format: jpg
            filters:
                upscale:   { min:  [150, 150] }
                thumbnail: { size: [150, 150], mode: outbound, allow_upscale: true }
        file_large:
            data_loader: stream.amazon_s3
            quality: 100
            format: jpg
            filters:
                upscale:   { min:  [900, 900] }
                thumbnail: { size: [900, 900], mode: inset, allow_upscale: true }
```

Just wanted to report this issue.

Please advise.
